"""Compute MLB matchup predictor constants from Supabase.

One-time script that queries:
1. ELO_DISTRIBUTION: per-dimension mean/std for z-score normalization
2. LEAGUE_AVERAGES: result_type base rates from plate_appearances

Output: JSON to paste into frontend/src/lib/matchupPredictor.ts
"""
import json
import os
from collections import Counter

from dotenv import load_dotenv
from supabase import create_client

load_dotenv()

client = create_client(os.environ["SUPABASE_URL"], os.environ["SUPABASE_KEY"])

# ---------- 1. ELO Distribution ----------

print("=== Querying talent_player_current for ELO distribution ===")
rows = []
offset = 0
page_size = 1000
while True:
    resp = (
        client.table("talent_player_current")
        .select("talent_type, player_role, season_elo")
        .range(offset, offset + page_size - 1)
        .execute()
    )
    rows.extend(resp.data)
    if len(resp.data) < page_size:
        break
    offset += page_size

print(f"  Fetched {len(rows)} rows")

# Group by (talent_type, player_role) → list of season_elo
from collections import defaultdict
import statistics

groups: dict[tuple[str, str], list[float]] = defaultdict(list)
for r in rows:
    key = (r["talent_type"], r["player_role"])
    groups[key].append(r["season_elo"])

elo_distribution = {}
for (talent_type, player_role), elos in sorted(groups.items()):
    key = f"{player_role.upper()}_{talent_type.upper()}"
    mean = statistics.mean(elos)
    std = statistics.stdev(elos) if len(elos) > 1 else 100.0
    elo_distribution[key] = {"mean": round(mean, 1), "std": round(std, 1), "n": len(elos)}
    print(f"  {key}: mean={mean:.1f}, std={std:.1f}, n={len(elos)}")

# ---------- 2. League Averages ----------

print("\n=== Querying plate_appearances for league averages ===")
pa_rows = []
offset = 0
while True:
    resp = (
        client.table("plate_appearances")
        .select("result_type")
        .range(offset, offset + page_size - 1)
        .execute()
    )
    pa_rows.extend(resp.data)
    if len(resp.data) < page_size:
        break
    offset += page_size

print(f"  Fetched {len(pa_rows)} plate appearances")

counts = Counter(r["result_type"] for r in pa_rows)
total = sum(counts.values())

print(f"  Result type counts:")
for rt, c in sorted(counts.items(), key=lambda x: -x[1]):
    print(f"    {rt}: {c} ({c/total*100:.1f}%)")

# Classify outcomes
bb_count = counts.get("BB", 0) + counts.get("IBB", 0) + counts.get("HBP", 0)
k_count = counts.get("StrikeOut", 0)
hr_count = counts.get("HR", 0)
triple_count = counts.get("Triple", 0)
double_count = counts.get("Double", 0)
single_count = counts.get("Single", 0)
out_count = counts.get("OUT", 0) + counts.get("SAC", 0) + counts.get("E", 0)

# BIP = everything except BB and K
bip_count = total - bb_count - k_count
hit_count = single_count + double_count + triple_count + hr_count
xbh_count = double_count + triple_count + hr_count

league_averages = {
    "bb_rate": round(bb_count / total, 4),
    "k_rate": round(k_count / total, 4),
    "bip_rate": round(bip_count / total, 4),
    "hit_rate_on_bip": round(hit_count / bip_count, 4) if bip_count > 0 else 0.3,
    "xbh_rate_on_hit": round(xbh_count / hit_count, 4) if hit_count > 0 else 0.28,
    "2b_ratio": round(double_count / xbh_count, 4) if xbh_count > 0 else 0.6,
    "3b_ratio": round(triple_count / xbh_count, 4) if xbh_count > 0 else 0.06,
    "hr_ratio": round(hr_count / xbh_count, 4) if xbh_count > 0 else 0.34,
}

print(f"\n  League averages:")
for k, v in league_averages.items():
    print(f"    {k}: {v}")

# ---------- 3. Output as TypeScript ----------

print("\n\n========== TYPESCRIPT OUTPUT ==========\n")

print("// Auto-generated by scripts/compute_matchup_constants.py")
print("// Source: Supabase talent_player_current + plate_appearances (2025 season)")
print()
print("export const MLB_ELO_DISTRIBUTION: Record<string, { mean: number; std: number }> = " +
      json.dumps({k: {"mean": v["mean"], "std": v["std"]} for k, v in elo_distribution.items()}, indent=2) + ";")
print()
print("export const MLB_LEAGUE_AVERAGES = " + json.dumps(league_averages, indent=2) + ";")
