/**
 * Matchup Predictor V2.1 — pure TypeScript port of balltology-elo/src/matchup_predictor.py
 *
 * 3-Stage Decision Tree:
 *   Stage 1: 3-way Softmax → P(BB), P(K), P(BIP)
 *   Stage 2: Base-rate logistic → P(Hit|BIP), P(Out|BIP)
 *   Stage 3: Base-rate logistic → P(XBH|Hit), P(1B|Hit) → 2B/3B/HR split
 */
import type { BatterTalentElo, PitcherTalentElo, MatchupPrediction } from '../types/matchup';

// Auto-generated by scripts/compute_matchup_constants.py (2025 season)
const MLB_ELO_DISTRIBUTION: Record<string, { mean: number; std: number }> = {
  BATTER_CONTACT:          { mean: 1504.5, std: 33.9 },
  BATTER_POWER:            { mean: 1468.6, std: 61.6 },
  BATTER_DISCIPLINE:       { mean: 1700.3, std: 139.0 },
  PITCHER_STUFF:           { mean: 1587.3, std: 56.6 },
  PITCHER_BIP_SUPPRESSION: { mean: 1513.3, std: 18.2 },
  PITCHER_COMMAND:         { mean: 1681.1, std: 126.5 },
};

const MLB_LEAGUE_AVERAGES = {
  bb_rate: 0.0949,
  k_rate: 0.2218,
  bip_rate: 0.6834,
  hit_rate_on_bip: 0.3206,
  xbh_rate_on_hit: 0.3493,
  '2b_ratio': 0.5522,
  '3b_ratio': 0.0448,
  hr_ratio: 0.403,
};

const ZSCORE_DIVISOR = {
  stage1_bb: 3.5,
  stage1_k: 3.5,
  stage2: 5.0,
  stage3: 5.0,
};

const WOBA_WEIGHTS: Record<string, number> = {
  BB: 0.69,
  K: 0.0,
  OUT: 0.0,
  '1B': 0.88,
  '2B': 1.24,
  '3B': 1.56,
  HR: 2.00,
};

/** Convert ELO to z-score using dimension-specific distribution. */
function eloToZscore(elo: number, talentType: string): number {
  const dist = MLB_ELO_DISTRIBUTION[talentType];
  if (!dist || dist.std === 0) return 0.0;
  return (elo - dist.mean) / dist.std;
}

/** Base-rate logistic: shift logit of base_rate by z_diff/divisor. */
function zscoreToProbability(zDiff: number, divisor: number, baseRate: number): number {
  const baseLogit = Math.log(baseRate / (1.0 - baseRate));
  const logit = baseLogit + zDiff / divisor;
  return 1.0 / (1.0 + Math.exp(-logit));
}

/** Stage 1: 3-way Softmax (BB / K / BIP). */
function stage1Softmax(
  zDiscCmd: number,
  zStuffContact: number,
): { pBB: number; pK: number; pBIP: number } {
  const la = MLB_LEAGUE_AVERAGES;
  const bipRate = la.bip_rate;

  const baseLogitBB = Math.log(la.bb_rate / bipRate);
  const baseLogitK = Math.log(la.k_rate / bipRate);

  const logitBB = baseLogitBB + zDiscCmd / ZSCORE_DIVISOR.stage1_bb;
  const logitK = baseLogitK + zStuffContact / ZSCORE_DIVISOR.stage1_k;

  const expBB = Math.exp(logitBB);
  const expK = Math.exp(logitK);
  const Z = expBB + expK + 1.0;

  return { pBB: expBB / Z, pK: expK / Z, pBIP: 1.0 / Z };
}

/** Predict single plate appearance outcome probabilities. */
export function predictPlateAppearance(
  batter: BatterTalentElo,
  pitcher: PitcherTalentElo,
): MatchupPrediction {
  // Z-score conversion
  const zContact = eloToZscore(batter.contact, 'BATTER_CONTACT');
  const zPower = eloToZscore(batter.power, 'BATTER_POWER');
  const zDiscipline = eloToZscore(batter.discipline, 'BATTER_DISCIPLINE');

  const zStuff = eloToZscore(pitcher.stuff, 'PITCHER_STUFF');
  const zBipSupp = eloToZscore(pitcher.bipSuppression, 'PITCHER_BIP_SUPPRESSION');
  const zCommand = eloToZscore(pitcher.command, 'PITCHER_COMMAND');

  // Z-score diffs
  const zDiscCmd = zDiscipline - zCommand;       // batter discipline edge → BB↑
  const zStuffContact = zStuff - zContact;       // pitcher stuff edge → K↑
  const zContactBip = zContact - zBipSupp;       // batter contact edge → Hit↑

  // Stage 1: Softmax 3-way
  const s1 = stage1Softmax(zDiscCmd, zStuffContact);

  // Stage 2: Hit vs Out given BIP
  const pHitGivenBIP = zscoreToProbability(
    zContactBip,
    ZSCORE_DIVISOR.stage2,
    MLB_LEAGUE_AVERAGES.hit_rate_on_bip,
  );
  const pHit = s1.pBIP * pHitGivenBIP;
  const pOut = s1.pBIP * (1 - pHitGivenBIP);

  // Stage 3: XBH vs Single given Hit (power standalone)
  const pXBHGivenHit = zscoreToProbability(
    zPower,
    ZSCORE_DIVISOR.stage3,
    MLB_LEAGUE_AVERAGES.xbh_rate_on_hit,
  );
  const p1B = pHit * (1 - pXBHGivenHit);
  const pXBH = pHit * pXBHGivenHit;
  const p2B = pXBH * MLB_LEAGUE_AVERAGES['2b_ratio'];
  const p3B = pXBH * MLB_LEAGUE_AVERAGES['3b_ratio'];
  const pHR = pXBH * MLB_LEAGUE_AVERAGES.hr_ratio;

  const probabilities = {
    BB: s1.pBB,
    K: s1.pK,
    OUT: pOut,
    '1B': p1B,
    '2B': p2B,
    '3B': p3B,
    HR: pHR,
  };

  const expectedWoba = Object.entries(probabilities).reduce(
    (sum, [key, prob]) => sum + prob * (WOBA_WEIGHTS[key] ?? 0),
    0,
  );

  return {
    probabilities,
    expectedWoba,
    zDiffs: { zDiscCmd, zStuffContact, zContactBip, zPower },
    stages: {
      stage1: s1,
      stage2: { pHitGivenBIP, pOutGivenBIP: 1 - pHitGivenBIP },
      stage3: { pXBHGivenHit, p1BGivenHit: 1 - pXBHGivenHit },
    },
  };
}

/** League average expected wOBA (for comparison display). */
export const LEAGUE_AVG_WOBA = (() => {
  const la = MLB_LEAGUE_AVERAGES;
  const hitRate = la.bip_rate * la.hit_rate_on_bip;
  const p1B = hitRate * (1 - la.xbh_rate_on_hit);
  const pXBH = hitRate * la.xbh_rate_on_hit;
  return (
    la.bb_rate * 0.69 +
    p1B * 0.88 +
    pXBH * la['2b_ratio'] * 1.24 +
    pXBH * la['3b_ratio'] * 1.56 +
    pXBH * la.hr_ratio * 2.00
  );
})();
